### ISSUE TITLE
error:private_get_account_summary_get

### ISSUE THREAD

**Issue by chengxx1986** [deribit/deribit-api-clients#20]
I have got the bearer token,and "conf_auth.access_token = auth_data['result']['access_token']".
But when I'm executing the file，the following error occurred.
`
from __future__ import print_function
import requests
import openapi_client
from pprint import pprint

auth_key = "key"
auth_secret = "secret"
auth_url = "https://www.deribit.com/api/v2/public/auth"
auth_params = {
    'grant_type': 'client_credentials',
    'client_id': auth_key,
    'client_secret': auth_secret,
}

auth_read = requests.get(url=auth_url, params=auth_params)
auth_data = auth_read.json()
auth_access_token = auth_data['result']['access_token']

conf_auth = openapi_client.Configuration()
api_instance = openapi_client.AccountManagementApi(openapi_client.ApiClient(conf_auth))

currency = 'BTC'
extended = True

api_response = api_instance.private_get_account_summary_get(currency, extended=extended)
pprint(api_response)
`
errors:
Traceback (most recent call last):
  File "D:/python/test/deribit-v2/test-v2.py", line 29, in <module>
    api_response = api_instance.private_get_account_summary_get(currency, extended=extended)
  File "D:\python\test\deribit-v2\openapi_client\api\account_management_api.py", line 380, in private_get_account_summary_get
    return self.private_get_account_summary_get_with_http_info(currency, **kwargs)  # noqa: E501
  File "D:\python\test\deribit-v2\openapi_client\api\account_management_api.py", line 465, in private_get_account_summary_get_with_http_info
    collection_formats=collection_formats)
  File "D:\python\test\deribit-v2\openapi_client\api_client.py", line 341, in call_api
    _preload_content, _request_timeout, _host)
  File "D:\python\test\deribit-v2\openapi_client\api_client.py", line 172, in __call_api
    _request_timeout=_request_timeout)
  File "D:\python\test\deribit-v2\openapi_client\api_client.py", line 364, in request
    headers=headers)
  File "D:\python\test\deribit-v2\openapi_client\rest.py", line 239, in GET
    query_params=query_params)
  File "D:\python\test\deribit-v2\openapi_client\rest.py", line 229, in request
    raise ApiException(http_resp=r)
openapi_client.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Thu, 08 Aug 2019 07:52:43 GMT', 'Content-Type': 'application/json', 'Content-Length': '142', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Authorization,User-Agent,Range,X-Requested-With,Content-Type'})
HTTP response body: {"jsonrpc":"2.0","error":{"message":"unauthorized","code":13009},"testnet":false,"usIn":1565250763352975,"usOut":1565250763352992,"usDiff":17}

**Comment by lacksfish** [comment]
Make sure you are authenticated properly and that your API keys have `read` credentials on `account`.
